CREATE TABLE Host (
	id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	Name VARCHAR(255) NOT NULL,
	LastPowerState VARCHAR(20),
	LastPowerTime DATETIME
	);

CREATE TABLE LogEntry (
	Host INTEGER NOT NULL,
	Posted DATETIME NOT NULL,
	Message VARCHAR(4000) NOT NULL
	);

CREATE TABLE PowerStats (
	Host INTEGER NOT NULL,
	Period CHAR(1) NOT NULL,
	PeriodStart DATE NOT NULL,
	TimeAwake INTEGER NOT NULL,
	TimeScreenOff INTEGER NOT NULL,
	TimeSleep INTEGER NOT NULL,
	TimeOff INTEGER NOT NULL,
	PRIMARY KEY (Host,Period,PeriodStart)
	);
